//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlitterApp.DAL.DatabaseDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TweetLikeDislike
    {
        public int LDid { get; set; }
        public Nullable<int> TweetId { get; set; }
        public Nullable<int> LikedDislikedBy { get; set; }
        public string LikeDislike { get; set; }
    
        public virtual Tweet Tweet { get; set; }
        public virtual User User { get; set; }
        public virtual TweetLikeDislike TweetLikeDislike1 { get; set; }
        public virtual TweetLikeDislike TweetLikeDislike2 { get; set; }
    }
}
